"use client";
import {useEffect,useMemo,useState} from "react";
type Product={id:string;name:string;detail:string;price:number;stock:number;pack:string;color:string;emoji:string};
type Sale={id:string;time:string;total:number;payment:string;items:string};
type Booking={id:string;date:string;time:string;customer:string;phone:string;note:string};
const initial:Product[]=[
{id:"coca2",name:"Coca-Cola",detail:"Garrafa 2L",price:12,stock:36,pack:"6 pacotes × 6",color:"#e82924",emoji:"🥤"},
{id:"fanta2",name:"Fanta Laranja",detail:"Garrafa 2L",price:10,stock:18,pack:"3 pacotes × 6",color:"#f58220",emoji:"🍊"},
{id:"cocalata",name:"Coca-Cola",detail:"Lata",price:5,stock:24,pack:"4 pacotes × 6",color:"#b91c1c",emoji:"🥤"},
{id:"skilho",name:"Skilho",detail:"Unidade",price:5,stock:25,pack:"5 pacotes × 5",color:"#f2b705",emoji:"🍺"}];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=new Date().toISOString().slice(0,10);
export default function Home(){
 const[tab,setTab]=useState("caixa"),[products,setProducts]=useState(initial),[cart,setCart]=useState<Record<string,number>>({}),[sales,setSales]=useState<Sale[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[payment,setPayment]=useState("Pix"),[received,setReceived]=useState(""),[checkout,setCheckout]=useState(false),[toast,setToast]=useState("");
 const[form,setForm]=useState({date:today,time:"18:00",customer:"",phone:"",note:""});
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem("arena-caixa-v1")||"null");if(d){setProducts(d.products||initial);setSales(d.sales||[]);setBookings(d.bookings||[])}}catch{}},[]);
 useEffect(()=>localStorage.setItem("arena-caixa-v1",JSON.stringify({products,sales,bookings})),[products,sales,bookings]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0),total=useMemo(()=>products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0),[cart,products]);
 const todaySales=sales.filter(s=>s.time.startsWith(new Date().toLocaleDateString("pt-BR"))),dayTotal=todaySales.reduce((s,x)=>s+x.total,0),change=Math.max(0,+received.replace(",",".")-total);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2500)};
 const add=(p:Product)=>{if((cart[p.id]||0)>=p.stock)return notify("Estoque insuficiente");setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))};
 const qty=(id:string,d:number)=>{const p=products.find(x=>x.id===id)!;setCart(c=>({...c,[id]:Math.max(0,Math.min(p.stock,(c[id]||0)+d))}))};
 const finish=()=>{if(payment==="Dinheiro"&&+received.replace(",",".")<total)return notify("Valor recebido é menor que o total");const now=new Date(),items=products.filter(p=>cart[p.id]).map(p=>`${cart[p.id]}x ${p.name} ${p.detail}`).join(", ");setSales(s=>[{id:crypto.randomUUID(),time:`${now.toLocaleDateString("pt-BR")} às ${now.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`,total,payment,items},...s]);setProducts(ps=>ps.map(p=>({...p,stock:p.stock-(cart[p.id]||0)})));setCart({});setReceived("");setCheckout(false);notify("Venda finalizada com sucesso!")};
 const saveBooking=(e:React.FormEvent)=>{e.preventDefault();setBookings(b=>[...b,{...form,id:crypto.randomUUID()}].sort((a,z)=>`${a.date}${a.time}`.localeCompare(`${z.date}${z.time}`)));setForm({date:today,time:"18:00",customer:"",phone:"",note:""});notify("Horário reservado!")};
 return <main><header className="topbar"><div className="brand"><span>A</span><div><b>ARENA</b><small>Caixa & Agenda</small></div></div><div className="headeractions"><div className="open"><i/> Caixa aberto</div><a className="logout" href="/api/logout">Sair</a></div></header><section className="content">
 {tab==="caixa"&&<><Title over="OLÁ, BEM-VINDO 👋" title="Nova venda" side={new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}/><div className="summary"><Metric label="Vendas hoje" value={`${todaySales.length}`}/><Metric label="Total hoje" value={money(dayTotal)}/><Metric label="Itens em estoque" value={`${products.reduce((a,p)=>a+p.stock,0)}`}/></div><div className="sectionhead"><h2>Toque para adicionar</h2><span>{count} itens</span></div><div className="productgrid">{products.map(p=><button className="product" key={p.id} onClick={()=>add(p)} disabled={!p.stock}><div className="visual" style={{background:`${p.color}14`}}><span>{p.emoji}</span><b style={{background:p.color}}>{p.stock}</b></div><div className="productcopy"><strong>{p.name}</strong><small>{p.detail}</small><b>{money(p.price)}</b></div><em>+</em></button>)}</div>{count>0&&<div className="cartbar"><div><small>{count} itens no pedido</small><strong>{money(total)}</strong></div><button onClick={()=>setCheckout(true)}>Ver pedido →</button></div>}</>}
 {tab==="agenda"&&<><Title over="ORGANIZAÇÃO" title="Horários" side={`${bookings.length} agendados`}/><form className="bookingform" onSubmit={saveBooking}><h2>Novo agendamento</h2><p>Registre aqui o que antes ficava no papel.</p><label>Nome do cliente<input required placeholder="Ex.: João" value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><div className="twocol"><label>Data<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Horário<input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label></div><label>Telefone<input inputMode="tel" placeholder="(00) 00000-0000" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Observação<input placeholder="Ex.: reserva da quadra" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="primary">Reservar horário</button></form><div className="sectionhead"><h2>Próximos horários</h2></div><div className="list">{bookings.length?bookings.map(b=><article className="booking" key={b.id}><div className="time"><b>{b.time}</b><small>{new Date(`${b.date}T12:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}</small></div><div><strong>{b.customer}</strong><small>{b.note||b.phone||"Sem observação"}</small></div><button onClick={()=>setBookings(x=>x.filter(i=>i.id!==b.id))}>×</button></article>):<Empty icon="🗓️" title="Nenhum horário anotado" text="Use o formulário acima para começar."/>}</div></>}
 {tab==="vendas"&&<><Title over="CONTROLE DO CAIXA" title="Vendas" side={`${sales.length} registros`}/><div className="bigmetric"><small>Total vendido</small><strong>{money(sales.reduce((a,s)=>a+s.total,0))}</strong><span>desde o primeiro registro</span></div><div className="list">{sales.length?sales.map(s=><article className="sale" key={s.id}><span>✓</span><div><strong>{s.items}</strong><small>{s.time} • {s.payment}</small></div><b>{money(s.total)}</b></article>):<Empty icon="🧾" title="Nenhuma venda ainda" text="As vendas finalizadas aparecerão aqui."/>}</div></>}
 {tab==="estoque"&&<><Title over="PRODUTOS E PREÇOS" title="Estoque" side={`${products.reduce((a,p)=>a+p.stock,0)} itens`}/><p className="hint">Toque nos valores para ajustar preço e quantidade quando fizer uma nova compra.</p><div className="list">{products.map(p=><article className="stock" key={p.id}><span style={{background:`${p.color}14`}}>{p.emoji}</span><div><strong>{p.name}</strong><small>{p.detail} • inicial: {p.pack}</small></div><label>Preço<input type="number" step=".5" min="0" value={p.price} onChange={e=>setProducts(ps=>ps.map(x=>x.id===p.id?{...x,price:+e.target.value}:x))}/></label><label>Qtd.<input type="number" min="0" value={p.stock} onChange={e=>setProducts(ps=>ps.map(x=>x.id===p.id?{...x,stock:+e.target.value}:x))}/></label></article>)}</div></>}
 </section><nav className="bottomnav">{[["caixa","▣","Caixa"],["agenda","▦","Horários"],["vendas","≡","Vendas"],["estoque","◈","Estoque"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}><span>{x[1]}</span>{x[2]}</button>)}</nav>
 {checkout&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setCheckout(false)}><section className="sheet"><div className="handle"/><div className="sheethead"><div><small>PEDIDO ATUAL</small><h2>Finalizar venda</h2></div><button onClick={()=>setCheckout(false)}>×</button></div><div className="cartitems">{products.filter(p=>cart[p.id]).map(p=><div className="cartitem" key={p.id}><span>{p.emoji}</span><div><strong>{p.name}</strong><small>{p.detail} • {money(p.price)}</small></div><div className="stepper"><button onClick={()=>qty(p.id,-1)}>−</button><b>{cart[p.id]}</b><button onClick={()=>qty(p.id,1)}>+</button></div></div>)}</div><div className="totalrow"><span>Total</span><strong>{money(total)}</strong></div><label className="paylabel">Forma de pagamento</label><div className="payments">{["Pix","Dinheiro","Cartão"].map(x=><button key={x} className={payment===x?"selected":""} onClick={()=>setPayment(x)}>{x==="Pix"?"◈":x==="Dinheiro"?"R$":"▭"}<span>{x}</span></button>)}</div>{payment==="Dinheiro"&&<div className="cash"><label>Valor recebido (R$)<input inputMode="decimal" placeholder="0,00" value={received} onChange={e=>setReceived(e.target.value)}/></label><div><span>Troco</span><strong>{money(change)}</strong></div></div>}<button className="finish" onClick={finish}>Confirmar venda • {money(total)}</button></section></div>}{toast&&<div className="toast">✓ {toast}</div>}</main>}
function Title({over,title,side}:{over:string;title:string;side:string}){return <div className="hello"><div><small>{over}</small><h1>{title}</h1></div><span className="datepill">{side}</span></div>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty">{icon}<strong>{title}</strong><small>{text}</small></div>}
